import Head from 'next/head'
import Feed from '../components/Feed'
import Sidebar from '../components/sidebar'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className='bg-black min-h-screen flex max-w-[1500px] mx-auto'>
        <Sidebar/>
        <Feed/>
        {/* widgets */}

        {/* Modal */}
      </main>
    </div>
  )
}

export async function setServerSideProps(){
  
}
