import Head from 'next/head'
import Feed from '../components/Feed'
import LandingPage from '../components/LandingPage';
import Sidebar from '../components/sidebar'
import { useAuth } from '../context/AuthContext';
import { getProviders, getSession, useSession } from "next-auth/react";

export default function Home({providers}) {
  const {user}=useAuth();

  const { data: session } = useSession()

  if(!session) return <LandingPage providers={providers}/>
  return (
    <div className="">
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className='bg-black min-h-screen flex max-w-[1500px] mx-auto'>
        <Sidebar/>
        <Feed/>
        {/* widgets */}

        {/* Modal */}
      </main>
    </div>
  )
}

export async function getServerSideProps(context){
  const providers= await getProviders();
  const session = await getSession(context);

  return {
    props:{
      providers,
      session,
    }
  }
}
